# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afc8fb2c483716d581db302df362a90ec8009a2386fd488a87bc0170f55808d16cb1bb23dce14ead2b8c69c781b8574d0ea26760573f81894a388d32f65aab3f

test:
  secret_key_base: ed98897e94ddf96775f930e0189fee8726051deb9553ad6e065b955a8d5b994d0826a2c6f337a00bc640a40f1606c361ce21c2315dc6dff0c4ac230fe34d5901

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
